language: node_js
node_js:
  - 4.0.0
  - 4.1.0
  - 4.1.1
  - 4.1.2
  - 4.2.0
  - 4.2.1
  - 4.2.2
  - 4.2.3
  - 4.2.4
  - 4.2.5
  - 4.2.6
  - 4.3.0
  - 4.3.1
  - 4.3.2
  - 5.0.0
  - 5.1.0
  - 5.1.1
  - 5.2.0
  - 5.3.0
  - 5.4.0
  - 5.4.1
  - 5.5.0
  - 5.6.0
  - 5.7.0
  - 5.7.1
  - stable

script: npm test
